#!/usr/bin/env python3
"""Regenerate the core v3 golden fixtures (scoring_v2 core v3).

Writes two files next to this script:

* ``core_v3_golden.json`` — the frozen full return of
  ``path_scores.compute_domain_scores`` for each Appendix-A scenario.
* ``pool_domains_golden.json`` — the frozen full return of
  ``fop_pool.pool_domains`` for each Appendix-B scenario.

Both are regenerated by **replay**: the committed JSON's ``["scenario"]`` /
``["hyp_records"]`` / ``["pss"]`` blocks are kept verbatim, only ``["expected"]``
is recomputed and re-dumped. So the scenario inputs cannot drift, and the diff
against the hand-authored V3-0 fixture must be **empty** (that empty diff is the
proof the implementation matches the spec). If the diff is not empty, reconcile
the doc or the implementation — do not commit a bare regen.

Run from anywhere:  python gen_golden.py
"""
from __future__ import annotations

import json
from pathlib import Path

from _common import FIXTURE_DIR, _load, build_tree

ps = _load("path_scores")
fop = _load("fop_pool")


def _norm(d):
    """Match the tests' key normalisation (all dict keys -> str)."""
    if isinstance(d, dict):
        return {str(k): _norm(v) for k, v in d.items()}
    if isinstance(d, list):
        return [_norm(v) for v in d]
    return d


def _run_core(scn):
    root, _ = build_tree([tuple(e) for e in scn["edges"]], list(scn["node_ids"]))
    node_index = ps.build_node_index(root)
    pnd = {int(k): v for k, v in scn["posteriors"].items()}
    return ps.compute_domain_scores(
        scn["pair_details"], pnd, node_index, scn["scheme"]
    )


def _pss_map(rows):
    return {(h, int(dom)): float(w) for h, dom, w in rows} or None


def main():
    core_path = FIXTURE_DIR / "core_v3_golden.json"
    entries = json.loads(core_path.read_text())
    for e in entries:
        e["expected"] = _norm(_run_core(e["scenario"]))
    core_path.write_text(json.dumps(entries, indent=2) + "\n")
    print(f"core_v3_golden.json: {len(entries)} scenarios")

    pool_path = FIXTURE_DIR / "pool_domains_golden.json"
    pentries = json.loads(pool_path.read_text())
    for e in pentries:
        e["expected"] = _norm(
            fop.pool_domains(e["hyp_records"], _pss_map(e["pss"]))
        )
    pool_path.write_text(json.dumps(pentries, indent=2) + "\n")
    print(f"pool_domains_golden.json: {len(pentries)} scenarios")


if __name__ == "__main__":
    main()
