#!/bin/bash
set -Eeuo pipefail

# Generated by the PhyloPhere runner GUI — edit the project file and regenerate
# rather than hand-editing this file, unless you're making a one-off tweak.

# --- ARGUMENTS ---
TRAIT="${1:?Usage: $0 <TRAIT> [SECONDARY_TRAIT] [N_TRAIT] [C_TRAIT] [PRUNE_FILE] [PRUNE_SECONDARY_FILE] [TRAIT_TYPE]}"
SECONDARY_TRAIT="${2:-}"
N_TRAIT="${3:-}"
C_TRAIT="${4:-}"
PRUNE_FILE="${5:-}"
PRUNE_SECONDARY_FILE="${6:-}"
TRAIT_TYPE="${7:-}"   # "" / auto = infer, ordinal = coded fg/bg, continuous = force PSS

REPO_DIR="/home/miguel/IBE-UPF/PhD/PhyloPhere"
timestamp=$(date +%Y%m%d_%H%M%S)

# --- ENV ACTIVATION ---
set +u
if command -v micromamba >/dev/null 2>&1; then
    eval "$(micromamba shell hook --shell bash)"
    micromamba activate phylophere
elif [ -n "${CONDA_EXE:-}" ] || command -v conda >/dev/null 2>&1; then
    __base="$(conda info --base 2>/dev/null || dirname "$(dirname "${CONDA_EXE:-}")")"
    [ -f "$__base/etc/profile.d/conda.sh" ] && . "$__base/etc/profile.d/conda.sh"
    conda activate phylophere
fi
set -u

# Postproc mode determines RUN_TAG ("_exploratory"/"_complete"/"") first, so the
# pre-run Nextflow home/session/work directories below can key on ${TRAIT}${RUN_TAG}
# the same way RESULTS_BASE does -- otherwise the exploratory and complete passes for
# the same trait would share one NXF_HOME/RUN_DIR/WORK_DIR and reintroduce the exact
# history-database/session-cache lock collisions this setup exists to avoid.
if [ "${POSTPROC_MODE:-}" = "exploratory" ]; then
    RESULTS_BASE="${CAAS_OUTBASE}/${TRAIT}${TAG}_exploratory"
    RUN_TAG="_exploratory"
    # Exploratory only sweeps minlen_values x maxcaas_values and stops there — every
    # downstream module (and RER/FADE, neither of which even depend on postproc) waits
    # for the _complete pass. If RER/FADE are enabled in the project, they run there.
    RUN_ACCUMULATION=false
    RUN_VEP=false
    RUN_FADE=false
    RUN_RER=false
    RUN_SCORING=false
elif [ "${POSTPROC_MODE:-}" = "filter" ]; then
    RESULTS_BASE="${CAAS_OUTBASE}/${TRAIT}${TAG}_complete"
    RUN_TAG="_complete"
else
    RESULTS_BASE="${CAAS_OUTBASE}/${TRAIT}${TAG}"
    RUN_TAG=""
fi

# Setup unique Nextflow home directory to avoid file lock collisions on history database
export NXF_HOME="$WORK_BASE/.nextflow/.nextflow_${TRAIT}${RUN_TAG}"
mkdir -p "$NXF_HOME"
ln -sfn "/home/miguel/.nextflow/plugins" "$NXF_HOME/plugins"

# Create and cd into a unique run directory to prevent Nextflow session/cache database lock collisions
RUN_DIR="$WORK_BASE/${TRAIT}${RUN_TAG}_nxf_run"
mkdir -p "$RUN_DIR"
cd "$RUN_DIR"

WORK_DIR="${WORK_BASE}/${TRAIT}${TAG}${RUN_TAG}"
mkdir -p "${RESULTS_BASE}" "${WORK_DIR}"

# --- PRECOMPUTED REUSE (Precomputed Run tab) ---
# Every path below is base_path/<TRAIT>/<known-subpath> — verified against each
# producing process's actual publishDir, see gui/models/precomputed.py's module
# docstring for the full table. Checking a box in the GUI both sets one of these
# and switches the corresponding module off (via that module's own enable_toggle,
# so RUN_* above already reflects it) — this block only supplies the *value* each
# module's existing precomputed-fallback branch (below) was already able to consume.
PRECOMP_OUTDIR="${PRECOMP_BASE_PATH:-}/${TRAIT}"
if [ ! -d "$PRECOMP_OUTDIR" ] && [ -d "${PRECOMP_BASE_PATH:-}/${TRAIT}_complete" ]; then
    PRECOMP_OUTDIR="${PRECOMP_BASE_PATH:-}/${TRAIT}_complete"
elif [ ! -d "$PRECOMP_OUTDIR" ] && [ -n "${TAG:-}${RUN_TAG:-}" ] && [ -d "${PRECOMP_BASE_PATH:-}/${TRAIT}${TAG:-}${RUN_TAG:-}" ]; then
    PRECOMP_OUTDIR="${PRECOMP_BASE_PATH:-}/${TRAIT}${TAG:-}${RUN_TAG:-}"
fi

if [ "${PRECOMP_USE_DISCOVERY:-false}" = true ]; then
    DISCOVERY_FROM="${PRECOMP_OUTDIR}/caastools/discovery.tab"
    # meta_caas/ is the current CT_META_CAAS publishDir; signification/ is the
    # pre-rename layout still on disk for outdirs from older runs.
    META_CAAS_FROM="${PRECOMP_OUTDIR}/meta_caas/meta_caas/global_meta_caas.tsv"
    [ -f "$META_CAAS_FROM" ] || META_CAAS_FROM="${PRECOMP_OUTDIR}/signification/meta_caas/global_meta_caas.tsv"
    [ -f "$META_CAAS_FROM" ] || META_CAAS_FROM="${PRECOMP_OUTDIR}/meta_caas/meta_caas/meta_caas.tsv"
    [ -f "$META_CAAS_FROM" ] || META_CAAS_FROM="${PRECOMP_OUTDIR}/signification/meta_caas/meta_caas.tsv"
    BACKGROUND_INPUT="${PRECOMP_OUTDIR}/caastools/background_genes.output"
    POSENRICH_BACKGROUND_FILE="${PRECOMP_OUTDIR}/caastools/background.output"
    # These only exist if the source run had --caas_permulation_enrichment on.
    # All four must be wired together: caas_perms.rds alone gives the FCS p.perm but
    # leaves the report's entire position-level permulation section empty, since that
    # section is gated on the per-position files. The reuse_exploratory branch above
    # sets the same four -- keep the two lists in sync.
    CAAS_PERMS_FILE="${PRECOMP_OUTDIR}/caas_permulation/caas_perms.rds"
    CAAS_POS_PVAL_FILE="${PRECOMP_OUTDIR}/caas_permulation/perm_pos_pval.tsv"
    CAAS_POS_SAMPLE_FILE="${PRECOMP_OUTDIR}/caas_permulation/perm_pos_sample.tsv"
    CAAS_POS_QUANTILES_FILE="${PRECOMP_OUTDIR}/caas_permulation/perm_pos_quantiles.tsv"
    # Triggers CAAS_PERMS_REBUILD in SCORING -- see the reuse_exploratory branch for why.
    CAAS_POS_DETAIL_FILE="${PRECOMP_OUTDIR}/caas_permulation/perm_pos_detail"
    [ -d "$CAAS_POS_DETAIL_FILE" ] || CAAS_POS_DETAIL_FILE="${PRECOMP_OUTDIR}/caas_permulation/perm_pos_detail.tsv.gz"  # legacy single-file layout
    [ -e "$CAAS_POS_DETAIL_FILE" ] || {
        echo "[WARN] perm_pos_detail missing: cannot rebuild the null, falling back to the cached caas_perms.rds (p.perm will be NA if it is stale)" >&2
        CAAS_POS_DETAIL_FILE=""
    }
fi
if [ "${PRECOMP_USE_RESAMPLE:-false}" = true ]; then
    RESAMPLE_FROM="${PRECOMP_OUTDIR}/caastools/resample.tab"
fi

if [ "${PRECOMP_USE_DISAMBIGUATION:-false}" = true ]; then
    DISAMBIGUATION_INPUT="${PRECOMP_OUTDIR}/ct_disambiguation/caas_convergence_master.csv"
    DISAMBIGUATION_DIR="${PRECOMP_OUTDIR}/ct_disambiguation"
fi

if [ "${PRECOMP_USE_POSTPROC:-false}" = true ]; then
    # gene_filtering/cleaned_backgrounds only exist if the source run had
    # gene_filter_mode != 'none' (the default).
    ACCUMULATION_CAAS_INPUT="${PRECOMP_OUTDIR}/postproc/gene_filtering/filtered_discovery.tsv"
    VEP_CAAS_INPUT="$ACCUMULATION_CAAS_INPUT"
    SCORING_POSTPROC_INPUT="$ACCUMULATION_CAAS_INPUT"
    ACCUMULATION_BACKGROUND_INPUT="${PRECOMP_OUTDIR}/postproc/cleaned_backgrounds/cleaned_background_main.txt"
    SCORING_BACKGROUND_INPUT="$ACCUMULATION_BACKGROUND_INPUT"
fi

if [ "${PRECOMP_USE_ACCUMULATION:-false}" = true ]; then
    SCORING_ACCUM_DIR="${PRECOMP_OUTDIR}/accumulation"
fi

if [ "${PRECOMP_USE_RER:-false}" = true ]; then
    RER_CONTINUOUS_FILE="${PRECOMP_OUTDIR}/rerconverge/rer_results/${TRAIT}.continuous.output"
    # perms RDS only exists if the source run's phenotype actually had permulation on.
    RER_PERMS_FILE="${PRECOMP_OUTDIR}/rerconverge/rer_results/${TRAIT}.continuous.perms.rds"
    SCORING_RER_PERMS_INPUT="$RER_PERMS_FILE"
    # Scoring's own RER fallback is RER_REPORT's rendered summary, not RER_CONT's raw
    # output above — different producer, filename carries a variable suffix so it's
    # resolved with a glob at generation time here rather than a fixed path.
    SCORING_RER_INPUT="$(ls "${PRECOMP_OUTDIR}/rerconverge/rer_results/"rerconverge_summary_*.tsv 2>/dev/null | head -n1 || true)"
fi

if [ "${PRECOMP_USE_FADE:-false}" = true ]; then
    FADE_JSON_DIR_TOP="${PRECOMP_OUTDIR}/selection/fade/top/json"
    FADE_JSON_DIR_BOTTOM="${PRECOMP_OUTDIR}/selection/fade/bottom/json"
    # summary/site TSVs are optional emits — only exist if FADE's report step actually
    # produced them for the source run.
    SCORING_FADE_SUMMARY_TOP="${PRECOMP_OUTDIR}/selection/fade/top/fade_summary_top.tsv"
    SCORING_FADE_SUMMARY_BOTTOM="${PRECOMP_OUTDIR}/selection/fade/bottom/fade_summary_bottom.tsv"
    SCORING_FADE_SITE_TOP="${PRECOMP_OUTDIR}/selection/fade/top/fade_site_bf_top.tsv"
    SCORING_FADE_SITE_BOTTOM="${PRECOMP_OUTDIR}/selection/fade/bottom/fade_site_bf_bottom.tsv"
fi

if [ "${PRECOMP_USE_VEP:-false}" = true ]; then
    # only exist if the source run had the matching DB (PrimateAI-3D/COSMIC) configured.
    SCORING_VEP_PRIMATEAI="${PRECOMP_OUTDIR}/vep/primateai_mapped.tsv"
    SCORING_VEP_COSMIC="${PRECOMP_OUTDIR}/vep/cosmic_scores.tsv"
fi

# Per-process cpus/memory overrides from the Resources tab's advanced table.
# Nextflow only reads these from a config file, never from --flags, so this is
# generated here and loaded last via -c below (last-defined selector wins),
# overriding conf/resources.config's own per-process defaults where set.
RESOURCES_OVERRIDE="$WORK_DIR/resources.override.config"
cat > "$RESOURCES_OVERRIDE" <<'EOF'
process {
    withLabel: 'process_low' {
        cpus   = { 1 }
        memory = { 500.MB }
    }
    withLabel: 'process_medium' {
        cpus   = { 2 }
        memory = { 4.GB }
    }
    withLabel: 'process_long_compute' {
        cpus   = { 1 }
        memory = { 4.GB * task.attempt }
    }
    withLabel: 'process_reporting' {
        cpus   = { 6 }
        memory = { 6.GB * task.attempt }
    }
    withLabel: 'process_reporting_phenotype' {
        cpus   = { 6 }
        memory = { 6.GB * task.attempt }
    }
    withLabel: 'process_reporting_dataset' {
        cpus   = { 4 }
        memory = { 4.GB * task.attempt }
    }
    withName: 'DATASET_PRUNE' {
        cpus   = { 4 }
        memory = { 12.GB * task.attempt }
    }
    withLabel: 'process_contrast_selection' {
        cpus   = { 6 }
        memory = { 4.GB * task.attempt }
    }
    withName: 'PHENOTYPE_EXPLORATION' {
        cpus   = { 6 }
        memory = { 6.GB * task.attempt }
    }
    withName: 'DATASET_EXPLORATION' {
        cpus   = { 4 }
        memory = { 4.GB * task.attempt }
    }
    withName: 'CONTRAST_ALGORITHM' {
        cpus   = { 6 }
        memory = { 4.GB * task.attempt }
    }
    withName: 'CI_COMPOSITION_REPORT' {
        cpus   = { 6 }
        memory = { 4.GB * task.attempt }
    }
    withName: 'DERIVE_ALI_SP_NAMES' {
        cpus   = { 2 }
        memory = { 4.GB * task.attempt }
    }
    withName: 'TREE_CLEANUP' {
        cpus   = { 1 }
        memory = { 500.MB * task.attempt }
    }
    withLabel: 'process_discovery' {
        cpus   = { 1 }
        memory = { 2.GB }
    }
    withLabel: 'process_resample' {
        cpus   = { 6 }
        memory = { 4.GB }
    }
    withLabel: 'process_perm_replay' {
        cpus   = { 1 }
        memory = { 12.GB }
    }
    withName: 'DISCOVERY_BATCHED' {
        cpus   = { 4 }
        memory = { 2.GB * task.attempt }
    }
    withLabel: 'process_discovery_batched' {
        cpus   = { 4 }
        memory = { 2.GB * task.attempt }
    }
    withLabel: 'process_perm_replay_batched' {
        cpus   = { 6 }
        memory = { 12.GB * task.attempt }
    }
    withName: 'CONCAT_DISCOVERY' {
        cpus   = { 2 }
        memory = { 2.GB * task.attempt }
    }
    withName: 'CONCAT_BACKGROUND' {
        cpus   = { 2 }
        memory = { 2.GB * task.attempt }
    }
    withName: 'CONCAT_RESAMPLE' {
        cpus   = { 2 }
        memory = { 2.GB * task.attempt }
    }
    withName: 'CHECK_MIN_CONTRASTS' {
        cpus   = { 1 }
        memory = { 2.GB * task.attempt }
    }
    withName: 'CT_FILTER' {
        cpus   = { 2 }
        memory = { 2.GB * task.attempt }
    }
    withLabel: 'CT_FILTER' {
        cpus   = { 2 }
        memory = { 4.GB * task.attempt }
    }
    withName: 'CAAS_FILTER_GENES' {
        cpus   = { 2 }
        memory = { 2.GB * task.attempt }
    }
    withName: 'CAAS_BACKGROUND_CLEANUP' {
        cpus   = { 2 }
        memory = { 2.GB * task.attempt }
    }
    withName: 'CT_FILTER_SUMMARY' {
        cpus   = { 2 }
        memory = { 4.GB * task.attempt }
    }
    withName: 'CT_POSTPROC_REPORT' {
        cpus   = { 6 }
        memory = { 6.GB * task.attempt }
    }
    withName: 'CAAS_SIGNIFICANCE_REPORT' {
        cpus   = { 6 }
        memory = { 4.GB * task.attempt }
    }
    withName: 'CT_DISAMBIGUATION_RUN' {
        cpus   = { 6 }
        memory = { 8.GB * task.attempt }
    }
    withName: 'CT_DISAMBIGUATION_SPLIT_GENES' {
        cpus   = { 1 }
        memory = { 2.GB * task.attempt }
    }
    withName: 'CT_DISAMBIGUATION_RUN_BATCHED' {
        cpus   = { 4 }
        memory = { 3.GB * task.attempt }
    }
    withName: 'CT_DISAMBIGUATION_MERGE' {
        cpus   = { 2 }
        memory = { 4.GB * task.attempt }
    }
    withName: 'CT_DISAMBIGUATION_PLOTS' {
        cpus   = { 4 }
        memory = { 8.GB * task.attempt }
    }
    withName: 'CAAS_PERMS_DISAMBIGUATE' {
        cpus   = { 6 }
        memory = { 12.GB * task.attempt }
    }
    withName: 'CAAS_PERMS_DISAMBIGUATE_BATCHED' {
        cpus   = { 4 }
        memory = { 20.GB * task.attempt }
    }
    withName: 'CAAS_PERMS_MERGE_DETAIL' {
        cpus   = { 2 }
        memory = { 4.GB * task.attempt }
    }
    withName: 'CAAS_PERMS_AGGREGATE' {
        cpus   = { 1 }
        memory = { 12.GB * task.attempt }
    }
    withName: 'CAAS_PERMS_REBUILD' {
        cpus   = { 2 }
        memory = { 18.GB * task.attempt }
    }
    withName: 'EXTRACT_DISAMBIG_DIR' {
        cpus   = { 2 }
        memory = { 2.GB * task.attempt }
    }
    withName: 'ASR_ROBUSTNESS_REPORT' {
        cpus   = { 6 }
        memory = { 4.GB * task.attempt }
    }
    withName: 'CT_ACCUMULATION_AGGREGATE' {
        cpus   = { 6 }
        memory = { 8.GB  * task.attempt }
    }
    withName: 'CT_ACCUMULATION_RANDOMIZE' {
        cpus   = { 6 }
        memory = { 12.GB * task.attempt }
    }
    withName: 'ACCUMULATION_REPORT' {
        cpus   = { 6 }
        memory = { 4.GB * task.attempt }
    }
    withName: 'ACCUMULATION_GENE_LISTS' {
        cpus   = { 1 }
        memory = { 500.MB * task.attempt }
    }
    withName: 'EXTRACT_EXTREME_SPECIES' {
        cpus   = { 1 }
        memory = { 1.GB * task.attempt }
    }
    withName: 'FILTER_FASTA_TO_TREE' {
        cpus   = { 1 }
        memory = { 1.GB * task.attempt }
    }
    withName: 'PREP_ALIGNMENTS' {
        cpus   = { 1 }
        memory = { 500.MB * task.attempt }
    }
    withName: 'PREP_ALIGNMENTS_BATCHED' {
        cpus   = { 6 }
        memory = { 2.GB * task.attempt }
    }
    withName: 'PHYLIP_TO_FASTA' {
        cpus   = { 1 }
        memory = { 2.GB * task.attempt }
    }
    withName: 'ANNOTATE_TREE_FG' {
        cpus   = { 6 }
        memory = { 4.GB * task.attempt }
    }
    withName: 'ANNOTATE_TREE_FG_BATCHED' {
        cpus   = { 6 }
        memory = { 8.GB * task.attempt }
    }
    withName: 'FADE_BATCHED' {
        cpus   = { 6 }
        memory = { 12.GB * task.attempt }
    }
    withName: 'COLLECT_GENE_SETS' {
        cpus   = { 2 }
        memory = { 4.GB * task.attempt }
    }
    withName: 'FADE_RUN' {
        cpus   = { 6 }
        memory = { 12.GB  * task.attempt }
    }
    withName: 'FADE_REPORT' {
        cpus   = { 6 }
        memory = { 8.GB * task.attempt }
    }
    withName: 'FADE_GENE_LISTS' {
        cpus   = { 1 }
        memory = { 500.MB * task.attempt }
    }
    withLabel: 'process_vep' {
        cpus   = { 4 }
        memory = { 8.GB * task.attempt }
    }
    withName: 'PRIMATEAI_MAP' {
        cpus   = { 2 }
        memory = { 12.GB * task.attempt }
    }
    withName: 'COSMIC_MAP' {
        cpus   = { 2 }
        memory = { 8.GB * task.attempt }
    }
    withName: 'ENSEMBL_VEP_ANNOTATE' {
        cpus   = { 2 }
        memory = { 4.GB  * task.attempt }
    }
    withName: 'RER_TRAIT' {
        cpus   = { 1 }
        memory = { 500.MB * task.attempt }
    }
    withName: 'RER_TREES' {
        cpus   = { 6 }
        memory = { 12.GB * task.attempt }
    }
    withName: 'RER_MATRIX' {
        cpus   = { 6 }
        memory = { 12.GB * task.attempt }
    }
    withName: 'RER_CONT' {
        cpus   = { 6 }
        memory = { 12.GB * task.attempt }
    }
    withName: 'RER_BIN' {
        cpus   = { 4 }
        memory = { 12.GB * task.attempt }
    }
    withName: 'RER_REPORT' {
        cpus   = { 6 }
        memory = { 8.GB * task.attempt }
    }
    withName: 'RER_GENE_LISTS' {
        cpus   = { 1 }
        memory = { 500.MB * task.attempt }
    }
    withName: 'SCORING_COMPUTE' {
        cpus   = { 6 }
        memory = { 8.GB * task.attempt }
    }
    withName: 'SCORING_REPORT' {
        cpus   = { 6 }
        memory = { 8.GB * task.attempt }
    }
    withName: 'SCORING_FCS_REPORT' {
        cpus   = { 6 }
        memory = { 12.GB * task.attempt }
    }
    withName: 'RER_FCS_REPORT' {
        cpus   = { 6 }
        memory = { 12.GB * task.attempt }
    }
    withName: 'SCORING_COMPARE_REPORT' {
        cpus   = { 6 }
        memory = { 12.GB * task.attempt }
    }
    withName: 'SCORING_AMI_REPORT' {
        cpus   = { 6 }
        memory = { 12.GB * task.attempt }
    }
    withName: 'POSENRICH_BUILD_GMT' {
        cpus   = { 6 }
        memory = { 12.GB * task.attempt }
    }
    withName: 'POSENRICH_RUN' {
        cpus   = { 6 }
        memory = { 12.GB * task.attempt }
    }
    withLabel: 'process_posenrich_batched' {
        cpus   = { 6 }
        memory = { 15.GB * task.attempt }
    }
    withName: 'POSENRICH_PREP_NULL' {
        cpus   = { 4 }
        memory = { 9.GB * task.attempt }
    }
}
EOF

# =============================================================================
# RESOLVE CONDITIONAL VALUES
# =============================================================================
# All module toggles are resolved to shell variables (true/false) BEFORE writing
# params.json. This replaces the old approach of conditionally appending flags to
# a bash NF_FLAGS array.
#
# Key design principle: ALL parameters are included in params.json unconditionally.
# When a module is off, its parameters still appear (matching conf/*.config defaults
# or as empty strings) — Nextflow ignores them because main.nf gates on the toggle.
# This eliminates all conditional NF_FLAGS+=() logic.

_RUN_REPORTING="${RUN_REPORTING:-true}"
_RUN_CAAS="${RUN_CAAS:-true}"
_RUN_DISAMBIGUATION="${RUN_DISAMBIGUATION:-true}"
_RUN_CT_POSTPROC="${RUN_CT_POSTPROC:-true}"
_RUN_ACCUMULATION="${RUN_ACCUMULATION:-false}"
_RUN_RER="${RUN_RER:-false}"
_RUN_FADE="${RUN_FADE:-true}"
_RUN_VEP="${RUN_VEP:-false}"
_RUN_SCORING="${RUN_SCORING:-true}"
_RUN_SCORING_STRESS="${RUN_SCORING_STRESS:-true}"
_RUN_ENRICHMENT="${RUN_ENRICHMENT:-true}"
_RUN_POSENRICH="${RUN_POSENRICH:-false}"
_ASR_ROBUSTNESS="${ASR_ROBUSTNESS:-true}"
_TOY_MODE="${TOY_MODE:-false}"

# CAAS: when enabled, pass the tool string; when off, an empty ct_tool disables the
# CT() workflow in main.nf (empty string is falsy in Groovy, unlike CLI's
# --ct_tool "" which becomes Boolean true). In JSON, "ct_tool": "" cleanly delivers
# an empty string — no --ct_tool= workaround needed.
if [ "$_RUN_CAAS" = true ]; then
    _CT_TOOL="discovery,resample"
else
    _CT_TOOL=""
fi

# Contrast selection is tracked separately from CAAS because it is the only producer
# of the fg/bg trait file (CHECK_MIN_CONTRASTS' traitfile_ok.tab), and that file is
# consumed by more than CT itself. CT_DISAMBIGUATION needs it to know which species
# are foreground vs background when it re-analyses convergence, so a run that reuses
# a precomputed CAAStools discovery but still computes disambiguation must keep
# contrast selection on — otherwise no trait file exists anywhere and main.nf stops
# with "CT disambiguation requires a trait file from CT/contrast_selection or
# --caas_config" (the GUI drives phenotypes through --my_traits and never sets
# --caas_config). Re-deriving it is safe: the contrast algorithm is deterministic
# given the same --my_traits and tree, so it reproduces the pairing the precomputed
# discovery was built on.
if [ "$_RUN_CAAS" = true ] || [ "$_RUN_DISAMBIGUATION" = true ]; then
    _CONTRAST_SELECTION=true
else
    _CONTRAST_SELECTION=false
fi

# RER tool string: only when RER is enabled.
if [ "$_RUN_RER" = true ]; then
    _RER_TOOL_STR="${RER_TOOL}"
else
    _RER_TOOL_STR=""
fi

# Resolve my_traits source, secondary/n/c traits, and pruning before writing
# params.json. Every field here is optional except TRAIT itself — the R side
# (subworkflows/TRAIT_ANALYSIS/local/src/{sample_size.R,commons.R}) branches on
# column-presence, not on any explicit class flag, so blanks pass through as-is.
_MY_TRAITS="$TRAIT_FILE"
_SECONDARY_TRAIT="$SECONDARY_TRAIT"
_N_TRAIT="$N_TRAIT"
_C_TRAIT="$C_TRAIT"
_TRAIT_TYPE="$TRAIT_TYPE"
if [ -n "$PRUNE_FILE" ]; then
    _PRUNE_DATA=true
    _PRUNE_LIST="${PRUNE_DIR}/${PRUNE_FILE}"
    _PRUNE_LIST_SECONDARY=""
    [ -n "$PRUNE_SECONDARY_FILE" ] && _PRUNE_LIST_SECONDARY="${PRUNE_DIR}/${PRUNE_SECONDARY_FILE}"
else
    _PRUNE_DATA=false
    _PRUNE_LIST=""
    _PRUNE_LIST_SECONDARY=""
fi

# =============================================================================
# WRITE params.json
# =============================================================================
# Nextflow's -params-file natively accepts JSON. All pipeline parameters go here
# instead of 50-100+ --flag arguments on the command line, which:
# 1. Exceeded the ~8,096-char shell command-line limit on some systems
# 2. Was rejected by Seqera Cloud (Tower) UI
#
# -params-file values UNCONDITIONALLY override conf/*.config defaults (higher
# priority) — confirmed empirically 2026-08-01: a key present in params.json with
# value "" permanently defeats that param's `?: "default"` Elvis line in conf/*.config,
# even though the exact same "" arriving via a bare CLI flag (`--flag=`) does NOT (CLI
# values apply at a lower tier that config's Elvis defaulting still runs on top of).
# This is NOT the same thing as omitting the key entirely — an absent key still lets
# the config default apply normally; it's specifically writing "" that burns in empty.
#
# Boolean values are unquoted true/false (valid JSON boolean literals).
# String values use shell $VAR expansion (heredoc is unquoted for this).
# For params whose real conf/*.config default IS "" by design (e.g. fade_postproc_top,
# trait_out) the ${VAR:-} fallback below is correct and intentional. But for any param
# whose config default is a real, non-empty value (e.g. lg_dat_path, gene_trees), the
# same ${VAR:-} pattern silently breaks it the moment the corresponding GUI field is
# left blank (the common/optional case) — hit for real with lg_dat_path (crashed
# fade.nf's unconditional `file(params.lg_dat_path)` with "Argument of `file` function
# cannot be empty" the first time a run left the LG matrix path at its default). Bake
# the real default into the bash fallback for any such param instead of leaving it "".

# Auto-generate tax_id / gene_ensembl_file when left blank (bin/resolve_core_inputs.py).
# Must happen here, in the invocation layer, not inside main.nf: Nextflow enforces
# single-assignment on params keys, so a params.tax_id = ... set after
# conf/common.config's own default has already run is silently ignored.
if [[ -z "${INPUT_TAX_ID:-}" || ( -z "${GENE_ENSEMBL_FILE:-}" && "${AUTO_GENERATE_ENSEMBL:-false}" == "true" ) ]]; then
    _CORE_INPUTS_RESOLVED="$(python3 "$REPO_DIR/bin/resolve_core_inputs.py" \
        --outdir "$RESULTS_BASE" --tree "$TREE_FILE" --alignment "$ALI_DIR" \
        --tax-id "${INPUT_TAX_ID:-}" --gene-ensembl-file "${GENE_ENSEMBL_FILE:-}" \
        $([ "${AUTO_GENERATE_ENSEMBL:-false}" == "true" ] && echo "--auto-generate-ensembl") \
        --ensembl-dataset "${ENSEMBL_DATASET:-}" \
        --ref-species "${REF_SPECIES_NAME:-Homo_sapiens}")"
    INPUT_TAX_ID="$(echo "$_CORE_INPUTS_RESOLVED" | grep '^TAX_ID=' | cut -d= -f2-)"
    GENE_ENSEMBL_FILE="$(echo "$_CORE_INPUTS_RESOLVED" | grep '^GENE_ENSEMBL_FILE=' | cut -d= -f2-)"
fi

# Resolve --gmt_dir when left blank: fetches current GO/Reactome/WikiPathways
# GMTs if AUTO_FETCH_GMT is true, falling back per-file to vendored copies in assets/gmt/
# (or copies vendored copies without network calls when false via --no-fetch).
if [[ -z "${GMT_DIR:-}" ]]; then
    _NO_FETCH_ARG=""
    if [[ "${AUTO_FETCH_GMT:-false}" != "true" ]]; then
        _NO_FETCH_ARG="--no-fetch"
    fi
    _GMT_RESOLVED="$(python3 "$REPO_DIR/bin/resolve_gmts.py" \
        --output-dir "$RESULTS_BASE/core_inputs/gmt" \
        --gmt-dir "${GMT_DIR:-}" \
        $_NO_FETCH_ARG)"
    GMT_DIR="$(echo "$_GMT_RESOLVED" | grep '^GMT_DIR=' | cut -d= -f2-)"
fi

PARAMS_JSON="$RUN_DIR/params.json"
cat > "$PARAMS_JSON" <<PARAMS_EOF
{
  "alignment": "$ALI_DIR",
  "ali_format": "${ALI_FORMAT:-fasta}",
  "ali_sp_names": "${ALI_SP_NAMES:-}",
  "tree": "$TREE_FILE",
  "outdir": "$RESULTS_BASE",
  "seed": "$SEED",
  "max_cpus": "$MAX_CPUS",
  "max_memory": "$MAX_MEMORY",
  "max_time": "$MAX_TIME",
  "sp_colname": "${SP_COLNAME:-species}",
  "clade_name": "${CLADE_NAME:-primates}",
  "clade_taxid": "${CLADE_TAXID:-9443}",
  "taxon_of_interest": "${TAXON_OF_INTEREST:-family}",
  "ref_species_name": "${REF_SPECIES_NAME:-Homo_sapiens}",
  "ref_species_taxid": "${REF_SPECIES_TAXID:-9606}",
  "tax_id": "${INPUT_TAX_ID:-}",
  "slurm_queue": "${SLURM_QUEUE:-haswell}",
  "slurm_queue_size": "8",
  "slurm_submit_rate_limit": "30/1min",
  "slurm_exit_read_timeout": "4h",

  "my_traits": "$_MY_TRAITS",
  "traitname": "$TRAIT",
  "secondary_trait": "$_SECONDARY_TRAIT",
  "n_trait": "$_N_TRAIT",
  "c_trait": "$_C_TRAIT",
  "branch_trait": "$BRANCH_TRAIT",
  "trait_type": "$_TRAIT_TYPE",
  "prune_data": $_PRUNE_DATA,
  "prune_list": "$_PRUNE_LIST",
  "prune_list_secondary": "$_PRUNE_LIST_SECONDARY",

  "reporting": $_RUN_REPORTING,
  "toy_mode": $_TOY_MODE,
  "toy_n": "$TOY_N",

  "contrast_selection": $_CONTRAST_SELECTION,
  "ct_tool": "$_CT_TOOL",
  "caas_config": "$CAAS_CONFIG",
  "patterns": "${PATTERNS:-1,2,3}",
  "caas_permulation_enrichment": true,
  "caas_full_perms": "$CAAS_FULL_PERMS",
  "pss_top_pct": "${PSS_TOP_PCT:-0.01}",
  "max_contrasts": "${MAX_CONTRASTS:-0}",
  "min_contrasts": "${MIN_CONTRASTS:-3}",
  "publish_intermediates": false,
  "ct_discovery_batch_size": "${CT_DISCOVERY_BATCH_SIZE:-25}",
  "ct_perm_replay_batch_size": "${CT_PERM_REPLAY_BATCH_SIZE:-10}",
  "ct_disambig_perms_batch_size": "${CT_DISAMBIG_PERMS_BATCH_SIZE:-1}",
  "min_divergent_fraction": "${MIN_DIVERGENT_FRACTION:-0.5}",
  "max_bg_gaps_fraction": "${MAX_BG_GAPS_FRACTION:-0.0}",
  "max_fg_gaps_fraction": "${MAX_FG_GAPS_FRACTION:-0.0}",
  "max_gaps_fraction": "${MAX_GAPS_FRACTION:-0.0}",
  "max_bg_miss_fraction": "${MAX_BG_MISS_FRACTION:-0.0}",
  "max_fg_miss_fraction": "${MAX_FG_MISS_FRACTION:-0.0}",
  "max_miss_fraction": "${MAX_MISS_FRACTION:-0.0}",
  "miss_pair": true,
  "caap_mode": true,
  "resample_use_n": true,
  "perm_strategy": "${PERM_STRATEGY:-BM}",
  "max_tries": "${MAX_TRIES:-1000000}",
  "chunk_size": "${CHUNK_SIZE:-500}",
  "include_b0": false,
  "multi_hypothesis": true,
  "max_fop": "${MAX_FOP:-100}",
  "caas_perms_fop": true,
  "export_groups": false,
  "export_perm_discovery": false,
  "discovery_from": "${DISCOVERY_FROM:-}",
  "resample_from": "${RESAMPLE_FROM:-}",

  "ct_disambiguation": $_RUN_DISAMBIGUATION,
  "ct_postproc": $_RUN_CT_POSTPROC,
  "asr_robustness": $_ASR_ROBUSTNESS,
  "ct_disambig_asr_mode": "$ASR_MODE",
  "ct_disambig_asr_model": "${ASR_MODEL:-lg}",
  "ct_disambig_asr_cache_dir": "${ASR_CACHE_DIR:-$REPO_DIR/caches/.asr_cache}",
  "ct_disambig_posterior_threshold": "${POSTERIOR_THRESHOLD:-0.1}",
  "ct_disambig_max_tasks_per_child": "${MAX_TASKS_PER_CHILD:-50}",
  "ct_disambig_batch_size": "${DISAMBIG_BATCH_SIZE:-1}",
  "meta_caas_from": "${META_CAAS_FROM:-}",
  "disambiguation_input": "${DISAMBIGUATION_INPUT:-}",
  "disambiguation_dir": "${DISAMBIGUATION_DIR:-}",
  "background_input": "${BACKGROUND_INPUT:-}",

  "caas_postproc_mode": "$POSTPROC_MODE",
  "filter_minlen": "$POSTPROC_MINLEN",
  "filter_maxcaas": "$POSTPROC_MAXCAAS",
  "gene_filter_mode": "$POSTPROC_GENE_FILTER_MODE",
  "minlen_values": "${POSTPROC_MINLEN_VALUES:-2,3,4,10}",
  "maxcaas_values": "${POSTPROC_MAXCAAS_VALUES:-0.6,0.7,0.8}",
  "extreme_threshold": "${POSTPROC_EXTREME_THRESHOLD:-0.99}",
  "iqr_multiplier": "${POSTPROC_IQR_MULTIPLIER:-3.0}",
  "gene_ensembl_file": "${GENE_ENSEMBL_FILE:-}",
  "auto_generate_ensembl": ${AUTO_GENERATE_ENSEMBL:-false},
  "ensembl_dataset": "${ENSEMBL_DATASET:-}",

  "ct_accumulation": $_RUN_ACCUMULATION,
  "accumulation_n_randomizations": "$N_RANDOMIZATIONS",
  "accumulation_randomization_type": "${ACCUMULATION_RANDOMIZATION_TYPE:-cons_decile}",
  "accumulation_entropy_dir": "$ENTROPY_DIR",
  "accumulation_fdr": "${ACCUMULATION_FDR:-0.1}",
  "accumulation_caas_input": "${ACCUMULATION_CAAS_INPUT:-}",
  "accumulation_background_input": "${ACCUMULATION_BACKGROUND_INPUT:-}",

  "rer_tool": "$_RER_TOOL_STR",
  "gene_trees": "${GENE_TREES:-}",
  "rer_perm_batches": "${RER_PERM_BATCHES:-10}",
  "rer_perms_per_batch": "${RER_PERMS_PER_BATCH:-100}",
  "rer_minsp": "${RER_MINSP:-15}",
  "winsorizeRER": "${WINSORIZE_RER:-3}",
  "winsorizeTrait": "${WINSORIZE_TRAIT:-3}",
  "rer_trait_mode": "${RER_TRAIT_MODE:-auto}",
  "rer_binary_clade": "${RER_BINARY_CLADE:-all}",
  "rer_min_pos": "${RER_MIN_POS:-2}",
  "rer_pval_threshold": "${RER_PVAL_THRESHOLD:-0.05}",
  "rer_pval_column": "${RER_PVAL_COLUMN:-p.perm}",
  "rer_top_n_labels": "${RER_TOP_N_LABELS:-20}",
  "rer_transform": "${RER_TRANSFORM:-ha_logit}",
  "trait_out": "${TRAIT_OUT:-}",
  "trees_out": "${TREES_OUT:-}",
  "matrix_out": "${MATRIX_OUT:-}",
  "rer_universe_file": "${RER_UNIVERSE_FILE:-}",
  "rer_gene_scores": "${RER_GENE_SCORES:-}",
  "rer_continuous_file": "${RER_CONTINUOUS_FILE:-}",
  "rer_perms_file": "${RER_PERMS_FILE:-}",

  "fade": $_RUN_FADE,
  "fade_direction": "${FADE_DIRECTION:-both}",
  "fade_background_scope": "${FADE_BACKGROUND_SCOPE:-all}",
  "fade_species_file": "${FADE_SPECIES_FILE:-}",
  "selection_prep_batch_size": "${SELECTION_PREP_BATCH_SIZE:-500}",
  "fade_batch_size": "${FADE_BATCH_SIZE:-200}",
  "fade_bf_threshold": "${FADE_BF_THRESHOLD:-100}",
  "fade_model": "${FADE_MODEL:-LG}",
  "fade_method": "${FADE_METHOD:-Variational-Bayes}",
  "fade_grid": "${FADE_GRID:-20}",
  "fade_chains": "${FADE_CHAINS:-5}",
  "fade_chain_length": "${FADE_CHAIN_LENGTH:-2000000}",
  "fade_burn_in": "${FADE_BURN_IN:-1000000}",
  "fade_samples": "${FADE_SAMPLES:-1000}",
  "fade_concentration": "${FADE_CONCENTRATION:-0.5}",
  "fade_min_genes_for_heatmap": "${FADE_MIN_GENES_FOR_HEATMAP:-2}",
  "lg_dat_path": "${LG_DAT_PATH:-$REPO_DIR/subworkflows/SELECTION/local/dat/lg.dat}",
  "fade_universe_file": "${FADE_UNIVERSE_FILE:-}",
  "fade_json_dir_top": "${FADE_JSON_DIR_TOP:-}",
  "fade_json_dir_bottom": "${FADE_JSON_DIR_BOTTOM:-}",

  "scoring": $_RUN_SCORING,
  "scoring_stress": $_RUN_SCORING_STRESS,
  "scoring_window_size_bp": "${SCORING_WINDOW_SIZE_BP:-1000000}",
  "scoring_stress_top_n": "${SCORING_STRESS_TOP_N:-25}",
  "scoring_stress_rank_metric": "${SCORING_STRESS_RANK_METRIC:-spearman}",
  "scoring_position_top_pct": "${SCORING_POSITION_TOP_PCT:-0.10}",
  "scoring_gene_top_pct": "${SCORING_GENE_TOP_PCT:-0.10}",
  "scoring_pos_perm_p_thr": "${SCORING_POS_PERM_P_THR:-0.1}",
  "scoring_postproc_input": "${SCORING_POSTPROC_INPUT:-}",
  "scoring_accum_dir": "${SCORING_ACCUM_DIR:-}",
  "scoring_vep_primateai": "${SCORING_VEP_PRIMATEAI:-}",
  "scoring_background_input": "${SCORING_BACKGROUND_INPUT:-}",
  "scoring_rer_input": "${SCORING_RER_INPUT:-}",
  "scoring_fade_summary_top": "${SCORING_FADE_SUMMARY_TOP:-}",
  "scoring_fade_summary_bottom": "${SCORING_FADE_SUMMARY_BOTTOM:-}",
  "scoring_fade_site_top": "${SCORING_FADE_SITE_TOP:-}",
  "scoring_fade_site_bottom": "${SCORING_FADE_SITE_BOTTOM:-}",
  "scoring_vep_cosmic": "${SCORING_VEP_COSMIC:-}",
  "caas_perms_file": "${CAAS_PERMS_FILE:-}",
  "caas_pos_pval_file": "${CAAS_POS_PVAL_FILE:-}",
  "caas_pos_sample_file": "${CAAS_POS_SAMPLE_FILE:-}",
  "caas_pos_quantiles_file": "${CAAS_POS_QUANTILES_FILE:-}",
  "caas_pos_detail_file": "${CAAS_POS_DETAIL_FILE:-}",

  "vep": $_RUN_VEP,
  "vep_map_dir": "${MAP_DIR:-}",
  "vep_primateai_db": "${VEP_PRIMATEAI_DB:-}",
  "cosmic_db": "${COSMIC_DB:-}",
  "vep_caas_input": "${VEP_CAAS_INPUT:-}",
  "vep_ensembl": ${VEP_ENSEMBL:-false},
  "vep_cache_dir": "${VEP_CACHE_DIR:-}",
  "vep_species": "${VEP_SPECIES:-homo_sapiens}",
  "vep_assembly": "${VEP_ASSEMBLY:-GRCh38}",

  "enrichment": $_RUN_ENRICHMENT,
  "fcs_enabled": ${FCS_ENABLED:-true},
  "auto_fetch_gmt": ${AUTO_FETCH_GMT:-false},
  "gmt_dir": "${GMT_DIR:-}",
  "fcs_min_genes": "${FCS_MIN_GENES:-5}",
  "fcs_max_genes": "${FCS_MAX_GENES:-500}",
  "fcs_fdr": "${FCS_FDR:-0.15}",
  "fcs_pperm_thr": "${FCS_PPERM_THR:-0.025}",
  "fcs_top_n": "${FCS_TOP_N:-20}",
  "fcs_batch_size": "${FCS_BATCH_SIZE:-4}",
  "string_db_dir": "${STRING_DB_DIR:-}",
  "string_cache_dir": "${STRING_CACHE_DIR:-}",
  "string_species": "${STRING_SPECIES:-9606}",
  "scoring_ami": false,
  "scoring_string": false,
  "domino_network_score_thr": "${DOMINO_NETWORK_SCORE_THR:-700}",
  "domino_slice_thr": "${DOMINO_SLICE_THR:-0.3}",
  "domino_module_thr": "${DOMINO_MODULE_THR:-0.05}",
  "publish_domino_intermediates": false,
  "scoring_compare_fdr": "${SCORING_COMPARE_FDR:-0.15}",
  "scoring_compare_top_n": "${SCORING_COMPARE_TOP_N:-20}",
  "comparison_perm_null": true,
  "comparison_perm_stat": "${COMPARISON_PERM_STAT:-spearman}",
  "comparison_perm_topk": "${COMPARISON_PERM_TOPK:-0.05}",

  "posenrich": $_RUN_POSENRICH,
  "posenrich_domains": ${POSENRICH_DOMAINS:-true},
  "domain_variability_file": "${DOMAIN_VARIABILITY_FILE:-}",
  "domain_ref_species": "${DOMAIN_REF_SPECIES:-}",
  "posenrich_ucr": ${POSENRICH_UCR:-true},
  "ucr_positions_file": "${UCR_POSITIONS_FILE:-}",
  "posenrich_eggnog": ${POSENRICH_EGGNOG:-false},
  "eggnog_taxid": "${EGGNOG_TAXID:-}",
  "egg_members_file": "${EGG_MEMBERS_FILE:-}",
  "egg_annotations_file": "${EGG_ANNOTATIONS_FILE:-}",
  "fubar_sites_file": "${FUBAR_SITES_FILE:-}",
  "posenrich_min_size": "${POSENRICH_MIN_SIZE:-5}",
  "posenrich_max_size": "${POSENRICH_MAX_SIZE:-0}",
  "posenrich_padj_thr": "${POSENRICH_PADJ_THR:-0.15}",
  "posenrich_p_perm_thr": "${POSENRICH_P_PERM_THR:-0.025}",
  "posenrich_batch_size": "${POSENRICH_BATCH_SIZE:-4}",
  "posenrich_background_file": "${POSENRICH_BACKGROUND_FILE:-}"
}
PARAMS_EOF

# =============================================================================
# NEXTFLOW ENGINE FLAGS
# =============================================================================
# Only Nextflow engine flags (single-dash) go on the command line.
# All pipeline parameters (double-dash --param) are in params.json above.
NF_ENGINE=(
    -params-file "$PARAMS_JSON"
    -profile local
    -c "$RESOURCES_OVERRIDE"
    -w "$WORK_DIR"
)
if [ "${RUN_TOWER:-false}" = true ]; then
    NF_ENGINE+=( -with-tower )
fi
NF_RUN_NAME="${TRAIT}${RUN_TAG}_$(cat /proc/sys/kernel/random/uuid 2>/dev/null | tr -d '-' | cut -c1-8 || printf '%08x' $RANDOM)"
NF_ENGINE+=(
    -name "$NF_RUN_NAME"
    -with-report   "${RESULTS_BASE}/nextflow_report_${NF_RUN_NAME}.html"
    -with-trace    "${RESULTS_BASE}/nextflow_trace_${NF_RUN_NAME}.tsv"
    -with-timeline "${RESULTS_BASE}/nextflow_timeline_${NF_RUN_NAME}.html"
)
if [ "$RESUME" = 1 ]; then
    NF_ENGINE+=( -resume )
fi

# --- EXTRA FLAGS (pass-through from GUI's extra_flags fields) ---
# These are user-provided arbitrary Nextflow flags that can't go in params.json
# (they may include engine flags or override-specific params). Kept on the CLI
# so they take highest precedence over both params.json and config defaults.

echo "======================================================"
echo "Running Nextflow Single Phenotype: $TRAIT"
echo "SLURM TASK ID     : ${SLURM_ARRAY_TASK_ID:-n/a}"

echo "Profile           : local"
echo "Trait             : $TRAIT"
echo "Alignments        : $ALI_DIR"
echo "Output            : $RESULTS_BASE"
echo "Work dir          : $WORK_DIR"
echo "Params file       : $PARAMS_JSON"

echo "Resuming?         : $([ "$RESUME" = 1 ] && echo yes || echo 'no (clean run)')"
echo "======================================================"

nextflow run "${REPO_DIR}/main.nf" "${NF_ENGINE[@]}"

if [ -f "${RESULTS_BASE}/low_contrasts.skip" ]; then
    echo "Warning: Skipped '${TRAIT}': too few foreground contrasts."
    exit 0
fi

echo "Success: Completed $TRAIT"
