#!/usr/bin/env python3
# theme.py — Palette sourced live from the desktop, not a fixed color set.
# PhyloPhere | gui/

"""
The conda-packaged Qt6 this GUI runs on ships no native QStyle plugin (no Breeze,
no Windows11/macOS style — see run_gui.sh's QT_QPA_PLATFORMTHEME comment) and, on
this install, its xdgdesktopportal *platform-theme* plugin does not actually relay
anything from the desktop either: querying it returns Fusion's own stock palette
(#d6d2d0 window, accent #308cc6) regardless of what the desktop's real accent/
color-scheme is set to — confirmed by comparing against a direct
org.freedesktop.portal.Settings query, which returns the real values.

So this module talks to that same portal directly (org.freedesktop.portal.Settings,
namespace org.freedesktop.appearance — the desktop-agnostic standard GTK and Qt
apps alike are supposed to read: https://flatpak.github.io/xdg-desktop-portal/docs/doc-org.freedesktop.portal.Settings.html)
for the two values it actually standardizes: color-scheme (light/dark) and
accent-color. Everything else in the palette is generated by Qt's own built-in
QPalette(QColor) constructor from a neutral white/black seed appropriate to that
scheme — the same "derive a full palette from one seed color" mechanism Qt itself
has used since Qt4, and the documented fallback LibreOffice's own Qt6 VCL backend
uses when a native style plugin isn't available. No swatch in this file is a
picked-by-us brand color; the one color that carries real user intent (accent) is
read live, and the rest is Qt's own algorithm.

If the portal can't be reached (non-Linux, no portal running, gdbus missing), this
falls back to leaving QApplication's own default palette untouched rather than
inventing a substitute.
"""

# ── Standard library ──────────────────────────────────────────────────────────
import re
import shutil
import subprocess

# ── Third-party ───────────────────────────────────────────────────────────────
from PySide6.QtCore import Qt
from PySide6.QtGui import QColor, QPalette
from PySide6.QtWidgets import QApplication

_PORTAL_BUS = "org.freedesktop.portal.Desktop"
_PORTAL_PATH = "/org/freedesktop/portal/desktop"
_PORTAL_IFACE = "org.freedesktop.portal.Settings"
_APPEARANCE_NS = "org.freedesktop.appearance"

_ACCENT_RE = re.compile(r"\(([\d.eE+-]+),\s*([\d.eE+-]+),\s*([\d.eE+-]+)\)")
_UINT_RE = re.compile(r"uint32 (\d+)")


def _read_portal_setting(key: str) -> str | None:
    """Raw gdbus reply text for org.freedesktop.appearance's `key`, or None if the
    portal (or gdbus itself) isn't reachable. gdbus is a glib2 tool, present on
    essentially every Linux desktop (GNOME's own toolkit dependency) — used instead
    of PySide6.QtDBus because that binding doesn't expose primitive struct readers
    (QDBusArgument has no asDouble/asUInt32 in this PySide6 build) to unpack the
    doubly-nested variant org.freedesktop.portal.Settings.Read returns."""
    if not shutil.which("gdbus"):
        return None
    try:
        result = subprocess.run(
            [
                "gdbus", "call", "--session",
                "--dest", _PORTAL_BUS,
                "--object-path", _PORTAL_PATH,
                "--method", f"{_PORTAL_IFACE}.Read",
                _APPEARANCE_NS, key,
            ],
            capture_output=True, text=True, timeout=2,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    return result.stdout if result.returncode == 0 else None


def _system_accent() -> QColor | None:
    raw = _read_portal_setting("accent-color")
    if not raw:
        return None
    match = _ACCENT_RE.search(raw)
    if not match:
        return None
    r, g, b = (float(x) for x in match.groups())
    color = QColor.fromRgbF(r, g, b)
    return color if color.isValid() else None


def _system_is_dark() -> bool:
    """org.freedesktop.appearance color-scheme: 0=no preference, 1=dark, 2=light."""
    raw = _read_portal_setting("color-scheme")
    if raw:
        match = _UINT_RE.search(raw)
        if match:
            return match.group(1) == "1"
    # Portal unavailable: fall back to whatever Qt itself detected (works even
    # without a platform-theme plugin on some setups, and is still a live signal
    # rather than a guess).
    from PySide6.QtGui import QGuiApplication
    return QGuiApplication.styleHints().colorScheme() == Qt.ColorScheme.Dark


def _ensure_svg_assets() -> dict[str, str]:
    """Ensures SVG icons for checkmarks and chevrons exist in res/ and returns their absolute POSIX paths."""
    from pathlib import Path
    repo_dir = Path(__file__).resolve().parent.parent
    res_dir = repo_dir / "res"
    res_dir.mkdir(parents=True, exist_ok=True)

    check_white = res_dir / "checkbox_check_white.svg"
    if not check_white.is_file():
        check_white.write_text(
            '<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" '
            'fill="none" stroke="white" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round">'
            '<polyline points="20 6 9 17 4 12"/></svg>'
        )

    check_black = res_dir / "checkbox_check_black.svg"
    if not check_black.is_file():
        check_black.write_text(
            '<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" '
            'fill="none" stroke="black" stroke-width="3.5" stroke-linecap="round" stroke-linejoin="round">'
            '<polyline points="20 6 9 17 4 12"/></svg>'
        )

    chevron_light = res_dir / "chevron_down_light.svg"
    if not chevron_light.is_file():
        chevron_light.write_text(
            '<svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" '
            'fill="none" stroke="#475569" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">'
            '<polyline points="6 9 12 15 18 9"/></svg>'
        )

    chevron_dark = res_dir / "chevron_down_dark.svg"
    if not chevron_dark.is_file():
        chevron_dark.write_text(
            '<svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" '
            'fill="none" stroke="#94a3b8" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round">'
            '<polyline points="6 9 12 15 18 9"/></svg>'
        )

    return {
        "check_white": check_white.resolve().as_posix(),
        "check_black": check_black.resolve().as_posix(),
        "chevron_light": chevron_light.resolve().as_posix(),
        "chevron_dark": chevron_dark.resolve().as_posix(),
    }


def _build_qss(dark: bool, accent: QColor) -> str:
    assets = _ensure_svg_assets()

    accent_hex = accent.name()
    is_accent_light = accent.lightnessF() > 0.6
    text_on_accent = "#000000" if is_accent_light else "#ffffff"
    check_icon = assets["check_black"] if is_accent_light else assets["check_white"]

    h, s, v, a = accent.getHsv()
    accent_hover = QColor.fromHsv(h, max(0, s - 25), min(255, v + 25), a).name()

    if dark:
        win_bg = "#121214"
        card_bg = "#1f1f23"
        card_border = "#38383e"
        title_bg = "#1f1f23"
        title_fg = "#f4f4f5"

        input_bg = "#121214"
        input_hover_bg = "#18181c"
        input_focus_bg = "#121214"
        input_border = "#52525b"
        input_hover_border = "#71717a"
        input_fg = "#f4f4f5"
        placeholder_fg = "#71717a"

        checkbox_border = "#71717a"
        checkbox_hover_bg = "#27272a"

        button_bg = "#27272a"
        button_border = "#38383e"
        button_hover_bg = "#3f3f46"
        button_hover_border = "#52525b"
        button_pressed_bg = "#18181c"

        disabled_bg = "#18181c"
        disabled_border = "#27272a"
        disabled_fg = "#71717a"

        tab_bg = "#121214"
        tab_fg = "#a1a1aa"
        tab_hover_bg = "#1f1f23"

        table_grid = "#38383e"
        header_bg = "#121214"
        header_fg = "#d4d4d8"
        alt_row = "#18181c"

        scrollbar_track = "#121214"
        scrollbar_thumb = "#27272a"
        scrollbar_thumb_hover = "#3f3f46"
        chevron_icon = assets["chevron_dark"]
        toolbar_bg = "#1f1f23"
    else:
        win_bg = "#f4f4f5"
        card_bg = "#ffffff"
        card_border = "#d4d4d8"
        title_bg = "#ffffff"
        title_fg = "#18181b"

        input_bg = "#fafafa"
        input_hover_bg = "#ffffff"
        input_focus_bg = "#ffffff"
        input_border = "#a1a1aa"
        input_hover_border = "#71717a"
        input_fg = "#18181b"
        placeholder_fg = "#71717a"

        checkbox_border = "#a1a1aa"
        checkbox_hover_bg = "#e4e4e7"

        button_bg = "#fafafa"
        button_border = "#d4d4d8"
        button_hover_bg = "#e4e4e7"
        button_hover_border = "#a1a1aa"
        button_pressed_bg = "#d4d4d8"

        disabled_bg = "#f4f4f5"
        disabled_border = "#e4e4e7"
        disabled_fg = "#a1a1aa"

        tab_bg = "#e4e4e7"
        tab_fg = "#52525b"
        tab_hover_bg = "#f4f4f5"

        table_grid = "#e4e4e7"
        header_bg = "#f4f4f5"
        header_fg = "#52525b"
        alt_row = "#fafafa"

        scrollbar_track = "#f4f4f5"
        scrollbar_thumb = "#d4d4d8"
        scrollbar_thumb_hover = "#a1a1aa"
        chevron_icon = assets["chevron_light"]
        toolbar_bg = "#ffffff"

    return f"""
    QMainWindow, QDialog {{
        background-color: {win_bg};
        color: {input_fg};
    }}

    QGroupBox {{
        background-color: {card_bg};
        border: 1px solid {card_border};
        border-radius: 8px;
        margin-top: 24px;
        padding: 16px 14px 14px 14px;
        font-size: 13px;
    }}
    QGroupBox::title {{
        subcontrol-origin: margin;
        subcontrol-position: top left;
        left: 14px;
        top: 4px;
        padding: 2px 8px;
        background-color: {title_bg};
        color: {title_fg};
        font-weight: bold;
        border-radius: 4px;
    }}

    QLineEdit, QComboBox, QSpinBox, QDoubleSpinBox, QPlainTextEdit {{
        background-color: {input_bg};
        color: {input_fg};
        border: 1.5px solid {input_border};
        border-radius: 6px;
        padding: 6px 10px;
        selection-background-color: {accent_hex};
        selection-color: {text_on_accent};
    }}
    QLineEdit:hover, QComboBox:hover, QSpinBox:hover, QPlainTextEdit:hover {{
        border-color: {input_hover_border};
        background-color: {input_hover_bg};
    }}
    QLineEdit:focus, QComboBox:focus, QSpinBox:focus, QPlainTextEdit:focus {{
        border: 2px solid {accent_hex};
        background-color: {input_focus_bg};
    }}
    QLineEdit:disabled, QComboBox:disabled, QSpinBox:disabled, QPlainTextEdit:disabled {{
        background-color: {disabled_bg};
        color: {disabled_fg};
        border-color: {disabled_border};
    }}

    QComboBox::drop-down {{
        subcontrol-origin: padding;
        subcontrol-position: top right;
        width: 24px;
        border-left-width: 0px;
        border-top-right-radius: 6px;
        border-bottom-right-radius: 6px;
    }}
    QComboBox::down-arrow {{
        image: url('{chevron_icon}');
        width: 12px;
        height: 12px;
    }}
    QComboBox QAbstractItemView {{
        background-color: {card_bg};
        color: {input_fg};
        border: 1px solid {card_border};
        border-radius: 6px;
        selection-background-color: {accent_hex};
        selection-color: {text_on_accent};
        padding: 4px;
    }}

    QCheckBox {{
        spacing: 8px;
        color: {input_fg};
        font-weight: 500;
        padding: 3px 0px;
    }}
    QCheckBox::indicator {{
        width: 18px;
        height: 18px;
        border-radius: 4px;
        border: 1.5px solid {checkbox_border};
        background-color: {input_bg};
    }}
    QCheckBox::indicator:hover {{
        border-color: {accent_hex};
        background-color: {checkbox_hover_bg};
    }}
    QCheckBox::indicator:checked {{
        background-color: {accent_hex};
        border-color: {accent_hex};
        image: url('{check_icon}');
    }}
    QCheckBox::indicator:checked:hover {{
        background-color: {accent_hover};
        border-color: {accent_hover};
    }}
    QCheckBox::indicator:disabled {{
        border-color: {disabled_border};
        background-color: {disabled_bg};
    }}

    QPushButton {{
        background-color: {button_bg};
        color: {input_fg};
        border: 1px solid {button_border};
        border-radius: 6px;
        padding: 6px 14px;
        font-weight: 600;
    }}
    QPushButton:hover {{
        background-color: {button_hover_bg};
        border-color: {button_hover_border};
    }}
    QPushButton:pressed {{
        background-color: {button_pressed_bg};
    }}
    QPushButton:disabled {{
        background-color: {disabled_bg};
        color: {disabled_fg};
        border-color: {disabled_border};
    }}

    QTabWidget::pane {{
        border: 1px solid {card_border};
        border-radius: 8px;
        background-color: {card_bg};
        top: -1px;
    }}
    QTabBar::tab {{
        background-color: {tab_bg};
        color: {tab_fg};
        border: 1px solid {card_border};
        border-bottom: none;
        border-top-left-radius: 6px;
        border-top-right-radius: 6px;
        padding: 8px 16px;
        margin-right: 2px;
        font-weight: 500;
    }}
    QTabBar::tab:hover {{
        background-color: {tab_hover_bg};
    }}
    QTabBar::tab:selected {{
        background-color: {card_bg};
        color: {accent_hex};
        border-color: {card_border};
        border-bottom: 2px solid {accent_hex};
        font-weight: bold;
    }}

    QTableView {{
        background-color: {card_bg};
        color: {input_fg};
        gridline-color: {table_grid};
        border: 1px solid {card_border};
        border-radius: 6px;
        selection-background-color: {accent_hex};
        selection-color: {text_on_accent};
        alternate-background-color: {alt_row};
    }}
    QHeaderView::section {{
        background-color: {header_bg};
        color: {header_fg};
        padding: 6px 10px;
        font-weight: bold;
        border: none;
        border-bottom: 1px solid {card_border};
        border-right: 1px solid {card_border};
    }}

    QScrollBar:vertical {{
        border: none;
        background-color: {scrollbar_track};
        width: 10px;
        margin: 0px;
        border-radius: 5px;
    }}
    QScrollBar::handle:vertical {{
        background-color: {scrollbar_thumb};
        min-height: 20px;
        border-radius: 5px;
    }}
    QScrollBar::handle:vertical:hover {{
        background-color: {scrollbar_thumb_hover};
    }}
    QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {{
        height: 0px;
    }}
    QScrollBar:horizontal {{
        border: none;
        background-color: {scrollbar_track};
        height: 10px;
        margin: 0px;
        border-radius: 5px;
    }}
    QScrollBar::handle:horizontal {{
        background-color: {scrollbar_thumb};
        min-width: 20px;
        border-radius: 5px;
    }}
    QScrollBar::handle:horizontal:hover {{
        background-color: {scrollbar_thumb_hover};
    }}
    QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {{
        width: 0px;
    }}

    QToolBar {{
        background-color: {toolbar_bg};
        border-bottom: 1px solid {card_border};
        spacing: 6px;
        padding: 4px;
    }}
    QToolButton {{
        background-color: transparent;
        border: 1px solid transparent;
        border-radius: 4px;
        padding: 4px 8px;
        font-weight: 500;
        color: {input_fg};
    }}
    QToolButton:hover {{
        background-color: {button_hover_bg};
        border-color: {button_hover_border};
    }}

    QScrollArea {{
        border: none;
        background-color: transparent;
    }}
    """


def apply_theme(app: QApplication) -> None:
    """Force Fusion (the base style plugin available in this environment), seed its palette,
    and apply a modern QSS stylesheet providing clear shaded input boxes, custom checkboxes,
    card containers, and interactive highlights."""
    app.setStyle("Fusion")

    dark = _system_is_dark()
    seed = QColor(Qt.GlobalColor.black) if dark else QColor(Qt.GlobalColor.white)
    palette = QPalette(seed)

    accent = _system_accent()
    if accent is None:
        accent = QColor("#3b82f6") if dark else QColor("#2563eb")

    palette.setColor(QPalette.ColorRole.Highlight, accent)
    text_on_accent = Qt.GlobalColor.black if accent.lightnessF() > 0.6 else Qt.GlobalColor.white
    palette.setColor(QPalette.ColorRole.HighlightedText, QColor(text_on_accent))
    palette.setColor(QPalette.ColorRole.Link, accent)

    app.setPalette(palette)
    qss = _build_qss(dark, accent)
    app.setStyleSheet(qss)

