#!/bin/bash

# Generated by the PhyloPhere runner GUI — edit the project file and regenerate
# rather than hand-editing this file, unless you're making a one-off tweak.
#
# profile == 'slurm': submit this file with `sbatch` — SLURM sets
# SLURM_ARRAY_TASK_ID per array task and dispatch_phenotype below reads it once.
# profile == 'local': run this file directly with `bash` — no scheduler, no
# SLURM_ARRAY_TASK_ID, so it loops over every phenotype row itself and dispatches
# them sequentially instead.


# --- ENV ACTIVATION ---
set +u
if command -v micromamba >/dev/null 2>&1; then
    eval "$(micromamba shell hook --shell bash)"
    micromamba activate phylophere
elif [ -n "${CONDA_EXE:-}" ] || command -v conda >/dev/null 2>&1; then
    __base="$(conda info --base 2>/dev/null || dirname "$(dirname "${CONDA_EXE:-}")")"
    [ -f "$__base/etc/profile.d/conda.sh" ] && . "$__base/etc/profile.d/conda.sh"
    conda activate phylophere
fi
set -u

# --- GLOBAL RUN CONFIG ---
export RESUME="${RESUME:-0}"
export RUN_TOWER=false

if [ "false" = true ]; then
    export TAG="_toy"
    export TOY_MODE=true
    export TOY_N=""
    export CAAS_FULL_PERMS="100"
    # The draw budget must scale with the toy harvest target, not stay at the
    # full-run value: toy_mode subsamples alignments, never species, so the
    # permulation step still works on the full tree at the full acceptance
    # rate. 100 accepted needs well under 1k draws even under BM, so 20k is
    # generous headroom — and it caps a run that CANNOT fill the pool at ~1 min
    # instead of grinding through 1M draws plus two escalations before failing,
    # which would defeat the point of a smoke test.
    export MAX_TRIES="20000"
    export N_RANDOMIZATIONS="1000"
    export RER_PERM_BATCHES="10"
    export RER_PERMS_PER_BATCH="10"
else
    export TAG=""
    export TOY_MODE=false
    export TOY_N=""
    export CAAS_FULL_PERMS="${CAAS_FULL_PERMS:-1000}"
    export MAX_TRIES="100000"
    export N_RANDOMIZATIONS="1000000"
    export RER_PERM_BATCHES="10"
    export RER_PERMS_PER_BATCH="100"
fi

# --- INDIVIDUAL TOOL TOGGLES ---
# NOTE: no RUN_PRUNE here — pruning is per-phenotype-row now, triggered by that
# row's own PRUNE_FILE being set (see run_single.sh.j2), not a separate global
# toggle.
export RUN_REPORTING=true
export RUN_CAAS=true
export RUN_DISAMBIGUATION=true
export RUN_CT_POSTPROC=true
export RUN_ACCUMULATION=false
export RUN_RER=false
export RUN_FADE=true
export RUN_VEP=false
export RUN_SCORING=true
export RUN_SCORING_STRESS=true
export RUN_ENRICHMENT=true
export RUN_POSENRICH=true

# --- COMMON THINGS (shared across every phenotype in this batch) ---
export CAAS_OUTBASE="/home/miguel/IBE-UPF/PhD/PhyloPhere/validation/tier1/output/hb/results"
export WORK_BASE="/home/miguel/IBE-UPF/PhD/PhyloPhere/validation/tier1/output/hb/work"
export SEED="1998"
export MAX_CPUS="8"
export MAX_MEMORY="16.GB"
export MAX_TIME="5.day"
export SLURM_QUEUE=""

export ALI_DIR="/home/miguel/IBE-UPF/PhD/PhyloPhere/validation/tier1/input/hb/align"
export ALI_FORMAT="fasta"
export TREE_FILE="/home/miguel/IBE-UPF/PhD/PhyloPhere/validation/tier1/input/hb/tree.nwk"
export TRAIT_FILE="/home/miguel/IBE-UPF/PhD/PhyloPhere/validation/tier1/input/hb/my_traits.tsv"
export PRUNE_DIR=""
export BRANCH_TRAIT=""
export ALI_SP_NAMES=""
export INPUT_TAX_ID=""
export SP_COLNAME="species"
export CLADE_NAME="hb_altitude"
export TAXON_OF_INTEREST="family"

# --- CAAS ---
export CAAS_CONFIG=""
export PATTERNS="1,2,3"
export PSS_TOP_PCT="1"
export MAX_CONTRASTS="0"
export MIN_CONTRASTS="3"
export CT_DISCOVERY_BATCH_SIZE="25"
export CT_PERM_REPLAY_BATCH_SIZE="10"
export CT_DISAMBIG_PERMS_BATCH_SIZE="1"
export MIN_DIVERGENT_FRACTION="0.5"
export MAX_BG_GAPS_FRACTION="0.0"
export MAX_FG_GAPS_FRACTION="0.0"
export MAX_GAPS_FRACTION="0.0"
export MAX_BG_MISS_FRACTION="0.0"
export MAX_FG_MISS_FRACTION="0.0"
export MAX_MISS_FRACTION="0.0"
export PERM_STRATEGY="auto"
# MAX_TRIES is set in the toy_mode branch above, alongside CAAS_FULL_PERMS it has to track.
export CHUNK_SIZE="500"
export MAX_FOP="100"
export PRECOMP_BASE_PATH=""
export PRECOMP_USE_DISCOVERY="false"
export PRECOMP_USE_RESAMPLE="false"

# --- DISAMBIGUATION / POST-PROCESSING ---
export ASR_MODE="compute"
export ASR_MODEL="lg"
export ASR_CACHE_DIR=""
export POSTERIOR_THRESHOLD="0.1"
export MAX_TASKS_PER_CHILD="50"
export DISAMBIG_BATCH_SIZE="1"
export POSTPROC_MODE="filter"
export POSTPROC_MINLEN="3"
export POSTPROC_MAXCAAS="0.7"
export POSTPROC_GENE_FILTER_MODE="none"
export POSTPROC_MINLEN_VALUES="2,3,4,10"
export POSTPROC_MAXCAAS_VALUES="0.6,0.7,0.8"
export POSTPROC_EXTREME_THRESHOLD="0.99"
export POSTPROC_IQR_MULTIPLIER="3.0"
# --- STANDALONE / PRECOMPUTED UPSTREAM INPUTS ---
# Actual per-phenotype paths (base_path/<TRAIT>/...) are constructed in
# run_single.sh.j2, where $TRAIT is bound — see gui/models/precomputed.py's
# module docstring for the full path-template table.
export PRECOMP_USE_DISAMBIGUATION="false"
export PRECOMP_USE_POSTPROC="false"

# --- ACCUMULATION ---
export ACCUMULATION_RANDOMIZATION_TYPE="cons_decile"
export ENTROPY_DIR=""
export ACCUMULATION_FDR="0.05"
export PRECOMP_USE_ACCUMULATION="false"

# --- RERCONVERGE ---
export RER_TOOL="build_trait,build_tree,build_matrix,continuous"
export GENE_TREES="/home/miguel/IBE-UPF/PhD/PhyloPhere/validation/tier1/input/hb/gene_trees.nwk"
export TRAIT_OUT=""
export TREES_OUT=""
export MATRIX_OUT=""
export RER_MINSP="4"
export WINSORIZE_RER="3"
export WINSORIZE_TRAIT="3"
export RER_TRAIT_MODE="auto"
export RER_BINARY_CLADE="all"
export RER_MIN_POS="2"
export RER_PVAL_THRESHOLD="0.05"
export RER_PVAL_COLUMN="p.perm"
export RER_TOP_N_LABELS="20"
export RER_TRANSFORM="none"
export RER_UNIVERSE_FILE=""
export RER_GENE_SCORES=""
export PRECOMP_USE_RER="false"

# --- FADE ---
export FADE_DIRECTION="top"
export FADE_BACKGROUND_SCOPE="opposite"
export FADE_SPECIES_FILE=""
export SELECTION_PREP_BATCH_SIZE="500"
export FADE_BATCH_SIZE="200"
export FADE_BF_THRESHOLD="100"
export FADE_MODEL="LG"
export LG_DAT_PATH=""
export FADE_METHOD="Variational-Bayes"
export FADE_GRID="20"
export FADE_CHAINS="5"
export FADE_CHAIN_LENGTH="2000000"
export FADE_BURN_IN="1000000"
export FADE_SAMPLES="1000"
export FADE_CONCENTRATION="0.5"
export FADE_MIN_GENES_FOR_HEATMAP="2"
export FADE_UNIVERSE_FILE=""
export PRECOMP_USE_FADE="false"

# --- VEP ---
export VEP_PRIMATEAI_DB=""
export MAP_DIR=""
export COSMIC_DB=""
export VEP_ENSEMBL="true"
export VEP_CACHE_DIR=""
export VEP_SPECIES="homo_sapiens"
export VEP_ASSEMBLY="GRCh38"
export PRECOMP_USE_VEP="false"

# --- SCORING ---
export SCORING_WINDOW_SIZE_BP="1000000"
export GENE_ENSEMBL_FILE="/home/miguel/IBE-UPF/PhD/PhyloPhere/validation/tier1/input/hb/gene_ensembl.tsv"
export SCORING_STRESS_TOP_N="25"
export SCORING_STRESS_RANK_METRIC="spearman"
export SCORING_POSITION_TOP_PCT="0.10"
export SCORING_GENE_TOP_PCT="0.10"
export SCORING_POS_PERM_P_THR="0.05"

# --- ENRICHMENT / POSENRICH ---
export GMT_DIR=""
export FCS_MIN_GENES="5"
export FCS_MAX_GENES="500"
export FCS_FDR="0.15"
export FCS_PPERM_THR="0.025"
export FCS_TOP_N="20"
export FCS_BATCH_SIZE="4"
export STRING_DB_DIR=""
export STRING_CACHE_DIR=""
export STRING_SPECIES="9606"
export DOMINO_NETWORK_SCORE_THR="700"
export DOMINO_SLICE_THR="0.3"
export DOMINO_MODULE_THR="0.05"
export SCORING_COMPARE_FDR="0.15"
export SCORING_COMPARE_TOP_N="20"
export COMPARISON_PERM_STAT="spearman"
export COMPARISON_PERM_TOPK="0.05"
export EGG_MEMBERS_FILE="/home/miguel/IBE-UPF/PhD/PhyloPhere/validation/tier1/input/hb/eggnog/9443_members.tsv"
export EGG_ANNOTATIONS_FILE="/home/miguel/IBE-UPF/PhD/PhyloPhere/validation/tier1/input/hb/eggnog/9443_annotations.tsv"
export DOMAIN_VARIABILITY_FILE=""
export DOMAIN_REF_SPECIES="Aegithalos_bonvaloti"
export UCR_POSITIONS_FILE=""
export FUBAR_SITES_FILE="/home/miguel/IBE-UPF/PhD/PhyloPhere/validation/tier1/input/hb/positive_selection/fubar_sites.tsv"
export POSENRICH_MIN_SIZE="5"
export POSENRICH_MAX_SIZE="0"
export POSENRICH_PADJ_THR="0.15"
export POSENRICH_P_PERM_THR="0.025"
export POSENRICH_BATCH_SIZE="4"

REPO_DIR="/home/miguel/IBE-UPF/PhD/PhyloPhere"
SINGLE_RUNNER="${REPO_DIR}/run_tier1_hb_single_complete.sh"

# --- PHENOTYPE CATALOGUE ---
# Shared by both the SLURM-array and local-loop dispatch paths below: one bash
# function, called either once (SLURM sets $SLURM_ARRAY_TASK_ID itself) or in a
# sequential loop over every row (no scheduler locally, so this script IS the loop).
dispatch_phenotype() {
    local task_id="$1"
    case "$task_id" in
    1) TRAIT="elev_mid"; SECONDARY=""; NTRAIT=""; CTRAIT=""; PRUNE=""; PRUNE_SEC=""; TRAIT_TYPE="continuous"
        ;;
    2) TRAIT="altitude"; SECONDARY=""; NTRAIT=""; CTRAIT=""; PRUNE=""; PRUNE_SEC=""; TRAIT_TYPE="ordinal"
        ;;
    *)
        echo "Error: no phenotype row configured for task id '$task_id'" >&2
        return 1
        ;;
    esac

    echo "======================================================"
    echo " TASK ID       : $task_id"
    echo " TRAIT         : $TRAIT"
    echo "======================================================"

    bash "$SINGLE_RUNNER" "$TRAIT" "$SECONDARY" "$NTRAIT" "$CTRAIT" "$PRUNE" "$PRUNE_SEC" "$TRAIT_TYPE"
}

# Local runtime: no scheduler to set SLURM_ARRAY_TASK_ID or fan tasks out for us,
# so run every phenotype row sequentially, one after another, in this process.
for task_id in $(seq 1 2); do
    dispatch_phenotype "$task_id"
done
